// Package issue1469 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1469

import (
	"github.com/gofiber/fiber/v2"
	fibermid "github.com/oapi-codegen/oapi-codegen/v2/pkg/fibermid"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /test)
	Test(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// Test operation middleware
func (siw *ServerInterfaceWrapper) Test(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.Test(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/test", wrapper.Test)

}

// RegisterHandlerVersions - creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlerVersions(
	router fiber.Router,
	si ServerInterface,
	version string,
	apiHandlers map[string]map[string]fiber.Handler) map[string]map[string]fiber.Handler {
	return RegisterHandlerVersionsWithOptions(router, si, version, apiHandlers, FiberServerOptions{})
}

// RegisterHandlerVersionsWithOptions - creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlerVersionsWithOptions(
	router fiber.Router,
	si ServerInterface,
	version string,
	apiHandlers map[string]map[string]fiber.Handler,
	options FiberServerOptions) map[string]map[string]fiber.Handler {

	var wrapper = ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}
	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	if apiHandlers == nil {
		apiHandlers = make(map[string]map[string]fiber.Handler)
	}

	var versionedPath, latestPath string

	// /test
	versionedPath = "/" + version + "/test"
	if apiHandlers[versionedPath] == nil {
		apiHandlers[versionedPath] = make(map[string]fiber.Handler)
	}

	latestPath = "/" + fibermid.LatestVersion + "/test"
	if apiHandlers[latestPath] == nil {
		apiHandlers[latestPath] = make(map[string]fiber.Handler)
	}

	apiHandlers[versionedPath]["GET"] = wrapper.Test
	apiHandlers[latestPath]["GET"] = wrapper.Test

	return apiHandlers
}
